services:
  - type: web
    name: book-metadata-extractor
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: true
    plan: free    
